export const buttonConst = [
  { button_id: 'CE', buttonName: 'CE',operation:"" },
  { button_id: 'C', buttonName: 'C',operation:"" },
  { button_id: 'Back', buttonName: 'Back',operation:"" },
  { button_id: '/', buttonName: '/',operation:"" },
  { button_id: '7', buttonName: '7',operation:"" },
  { button_id: '8', buttonName: '8',operation:"" },
  { button_id: '9', buttonName: '9',operation:"", },
  { button_id: '*', buttonName: '*',operation:"" },
  { button_id: '4', buttonName: '4',operation:"" },
  { button_id: '5', buttonName: '5',operation:"" },
  { button_id: '6', buttonName: '6',operation:"" },
  { button_id: '-', buttonName: '-',operation:"" },
  { button_id: '1', buttonName: '1',operation:"" },
  { button_id: '2', buttonName: '2',operation:"" },
  { button_id: '3', buttonName: '3',operation:"" },
  { button_id: '+', buttonName: '+',operation:"" },
  { button_id: '%', buttonName: '%',operation:"" },
  { button_id: '0', buttonName: '0',operation:"" },
  { button_id: '.', buttonName: '.',operation:"" },
  { button_id: '=', buttonName: '=',operation:"" },
];
